### ISSUE TITLE
Importing segments results in script error (Versions 1.99.19/1.99.20)

### ISSUE THREAD

**Issue by tm67602** [knot126/Smash-Hit-Blender-Tools#6]
When I tried to import segments from Smash Hit into Blender, it resulted in a script error. This issue is present in versions 1.99.19 and 1.99.20. I had to revert to version 1.99.15 since it is stable. I do not know if versions 1.99.16, 1.99.17 and 1.99.18 have this problem. 

I tested this with multiple segments, all giving the same result. Below is two screenshots that I took before and after importing one of them. (I used the start segment from segments/hyperspace/fall)

Before Importing
https://user-images.githubusercontent.com/100551859/168470877-98f14bab-4bc5-4e6a-97a0-77b529a25155.PNG
After Importing
https://user-images.githubusercontent.com/100551859/168470879-3f2be9de-bf6d-4f7d-bd20-74a09b061a7b.PNG

The error log:

Python: Traceback (most recent call last):

  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_tools.py", line 813, in execute
    return sh_import_segment(self.filepath, context, True)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_tools.py", line 696, in sh_import_segment
    if (len(tile) == 1):
TypeError: object of type 'int' has no len()

location: <unknown location>:-1

**Comment by knot126** [comment]
This should be fixed in 1.99.21. Thanks for reporting!
